run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - bodyclose

linters-settings:
  goimports:
    local-prefixes: switchy
  revive:
    rules:
      - name: exported
        disabled: true
      - name: unused-parameter
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
